### ISSUE TITLE
Project build that works with back-end and static content

### ISSUE THREAD

**Issue by anymus0** [datapress-oss/dp-web#14]
@hemul011 

Create a script in *packages.json* that will build the front-end files with Parcel into the *dist* directory, right after it's finished it should automatically run the server.js as well so we can have a server that has both functional front-end and back-end. <br> This server will use **port 5000** as it is written on **line 25** in *server.js* <br>

It is important that we use *server.js* as our http server if we want the form to work with e-mails and not give an *error 404*.

**Comment by hemul011** [comment]
You can use the new npm run devserver script.
So you can test the email easier.
