### ISSUE TITLE
Implement module bundler

### ISSUE THREAD

**Issue by anymus0** [datapress-oss/dp-web#2]
Task: @hemul011 

- Remove Gulp (the task runner that is used by default)
- Add either [Webpack](https://webpack.js.org/) or [Parcel](https://parceljs.org/) and configure it
- Create 2 scripts inside _package.json_  1.: starts a dev session with live server.  2.: builds src to a prod version

**Comment by hemul011** [comment]
This is a broken version!!

Gulp got replaced by parcel which is a web application bundler. It offers fast performance utilizing multicore processing with zero configuration.

Hotfix needed for bootstrap import.

First, run:
the program has 2 scripts:
npm run dev //this is for installing the developer version
npm run build // this is for the finished version.

**Comment by datapress-hu** [comment]
For me `npm run dev` gives the following error:

```
> @ dev W:\projects\datapress\nyta\dp-web
> parcel index.html

Server running at http://localhost:1234
×  W:\projects\datapress\nyta\dp-web\vendor\bootstrap\css\bootstrap.min.css:undefined:undefined: ENOENT: no such file or directory, open 'W:\projects\datapress\nyta\dp-web\vendor\bootstrap\css\bootstrap.min.css'
Error: ENOENT: no such file or directory, open 'W:\projects\datapress\nyta\dp-web\vendor\bootstrap\css\bootstrap.min.css'
```

And Krisztián please be commitizen friendly when commiting!

**Comment by anymus0** [comment]
I've applied a fix: https://github.com/datapress-oss/dp-web/commit/8cb831f632c8cc2c2cf3f155833fabcc5eef8f7a

The problem was that with the removal of Gulp, Parcel wasn't able to find the npm dependencies like Bootstrap. It was explained in the [Parcel docs](https://parceljs.org/recipes.html#bootstrap-+-fontawesome) that importing these modules into a main.js entry point would be the solution. Parcel can automatically process these imports.
