### ISSUE TITLE
New dark mode theme

### ISSUE THREAD

**Issue by anymus0** [datapress-oss/dp-web#20]
- Design new dark mode

- Try out a design tool like [figma](https://www.figma.com/) to make sketching easier

**Comment by datapress-hu** [comment]
Try out this [one](https://hacks.mozilla.org/2019/10/video-shorts-from-mozilla-developer/) and make some tests. Use it if you like it.

**Comment by anymus0** [comment]
@hulitzacsaba @hemul011 
Implement the dark theme with your preferred method, for now two buttons or a switch is enough to do the job. Place it in the menu (desktop version only for now)
