### ISSUE TITLE
Making a new theme

### ISSUE THREAD

**Issue by anymus0** [datapress-oss/dp-web#4]
Task: @hulitzacsaba 

I think we should follow the material design patterns, first of all I found a [site](https://www.materialui.co/colors) where there are a lot of color schemes. Try to make new look by editing the scss files inside the assets folder. <br>
I'll post some design ideas later.

**Comment by hulitzacsaba** [comment]
As the commit description says, needs further feedback from other members so that I can improve on the style.

**Comment by anymus0** [comment]
Next we should include the logo on the top left corner instead of the "Start Bootstrap" text.
Here's the logo image(I've reworked the "data" word because the original was too pixelated):
<img width="60" height="60" src="https://user-images.githubusercontent.com/38496187/74106265-839b6200-4b65-11ea-97be-b3c2ec558985.png">

**Comment by datapress-hu** [comment]
I've added an svg file that contains the official logo of the Data-Press Kft. You can use it as you need.

**Comment by anymus0** [comment]
I've created a quick sketch, I think this would look good for the header:
![Untitled](https://user-images.githubusercontent.com/38496187/74589482-0a3cbd00-5006-11ea-8988-bb72fb324226.png)

**Comment by hulitzacsaba** [comment]
Agreed

**Comment by anymus0** [comment]
@hulitzacsaba At the bottom of the page the text "Kapcsolat" should also be red, and the icons' hover option on the footer should be a darker red instead of yellow.

**Comment by anymus0** [comment]
@hulitzacsaba Change the font color to red in the following classes: *h2.section-heading*, *text-muted* and also other texts that might be affected by the dark-theme.
