### ISSUE TITLE
Replace PHP form with nodejs equivalent

### ISSUE THREAD

**Issue by anymus0** [datapress-oss/dp-web#5]
Task: @hemul011 

The template's default form is written in PHP. Try to create a working version of the form's back-end in NodeJS.

**Comment by hemul011** [comment]
I found a module called [nodemailer](https://www.npmjs.com/package/nodemailer), this will replace the current PHP implementation that came by default with the template. This will allow us to send emails with the SMTP protocol, for testing we'll be using [Ethereal Email](https://nodemailer.com/smtp/testing/) which is recommended by the nodemailer's docs.

**Comment by hemul011** [comment]
I modified the contact_me.js and replaced it with a test version of the nodemailer. 
You can test it with: 
( node src/assets/js/contact_me.js )

**Comment by anymus0** [comment]
Ok, the next step will be to connect the html form with the backend.
[This article](https://medium.com/@binhchung48/create-a-contact-form-with-nodemailer-react-js-and-express-js-7757d41e2448) seems to be relevant, even though we well not use ReactJS.

**Comment by hemul011** [comment]
I connected the form to the ethereal.mail.You need to use the npm run build command, and use the npx nodemon to run the server.js in localhost.
You need to create a new account in ethereal.mail , paste your generated information into the let.transporter user and password field.

**Comment by anymus0** [comment]
I've just tested the form and it works like a charm, the[ build script](https://github.com/datapress-oss/dp-web/issues/14) is yet to be implemented though. <br>

## Manual test and how it works
HTTP server must be served by *server.js* which uses [ExpressJS](https://expressjs.com/) and not Parcel's [dev server](https://parceljs.org/cli.html). Parcel can only work with static content and it is still used for front-end development but for the sites full functionality and in production mode you need to run *server.js* so the back-end code can handle the request from the front-end!

- For this test I used a bash terminal because that is what I use, but I also got confirmation from @hemul011 that it works with windows Powershell as well.

### Steps:
#### 1.
Build the static content with Parcel. For this run the following: `npm run build` <br>
This will build the entire front-end, or rather, the *src/client/* directory into the *dist/* directory and the contents of this dist will be serverd by the http server inside *server.js*
#### 2.
So the static site is ready to use but if you just serve it as it is, then the Submit button on the form will respond with a 404 not found. <br> NodeJS has its own built in server, this is possible with the help of the [http module](https://nodejs.org/api/http.html). <br>
We can run all the back-end stuff that was written during the last weekend (*Email.js* and *server.js*) with the following command: `npx nodemon src/server/server.js` <br>
![1Screenshot from 2020-02-17 22 05 38](https://user-images.githubusercontent.com/38496187/74686426-cbf3f900-51d1-11ea-8429-6750e0d92ecd.png)


#### 3.
At this point the http server has started on **port 5000** and can be visited with a browser on localhost: http://localhost:5000/ <br>
Now we can test the form, fill it in and send it by clicking on the *SEND MESSAGE* button:
![2Screenshot from 2020-02-17 22 12 10](https://user-images.githubusercontent.com/38496187/74686690-93a0ea80-51d2-11ea-968d-284e0b41d77c.png) <br>

This will generate a link in the console pointing to the E-mail message that you'll get into your inbox.
Note.: for testing the E-mail we use [Ethereal.email](https://ethereal.email/). This is definitely not for production mode, but makes our testing a lot easier.

![3Screenshot from 2020-02-17 22 19 33](https://user-images.githubusercontent.com/38496187/74687122-c9929e80-51d3-11ea-9f9e-bf5023fd2415.png)

<br>
Now let's visit the generated link from the console and check our message that was sent from our website by filling in the form and clicking on the Submit button.: <br>

![4Screenshot from 2020-02-17 22 20 20](https://user-images.githubusercontent.com/38496187/74687248-28f0ae80-51d4-11ea-9560-db0e52c46362.png)

**Comment by hemul011** [comment]
You can use the new `npm run devserver` script.
So you can test the email easier.
