### ISSUE TITLE
Fix font-size on mobile

### ISSUE THREAD

**Issue by anymus0** [datapress-oss/dp-web#7]
Task: @hulitzacsaba 

inside: *_masthead.scss* and  *_page.scss*
- replace font-size units from px to rem
- decrease font-size for mobile view to fit screen

![Screenshot from 2020-02-08 15 00 26](https://user-images.githubusercontent.com/38496187/74086548-0815b400-4a84-11ea-98d6-38e9419eaf8e.png)

**Comment by hulitzacsaba** [comment]
Fixed and done.
