### ISSUE TITLE
Dark theme

### ISSUE THREAD

**Issue by anymus0** [datapress-oss/dp-web#9]
Task: @hulitzacsaba 

After we're finished tweaking the current theme, create a new *dark theme*, just a prototype for now. <br> If the proto succeeds we'll add a feature that will allow us to change between light/dark theme.

- Create this into a new bundle that relys on the same resources as the current one with just the colors being different.

**Comment by hulitzacsaba** [comment]
Made an experimental dark theme but you can't look at it now only if you change the files. The switch from #10 is alredy done I know but it needs to be fully implemented so you can look at the dark mode by a click of a button.

**Comment by datapress-hu** [comment]
The switch button (on/off) does not work for me. How can I try the dark theme out?

**Comment by hulitzacsaba** [comment]
The switch is not implemented fully so you can't look at the theme right now. !The switch doesn't work, but it will work,  its in the making!

**Comment by anymus0** [comment]
You can now check _main.js_ and as **line 13** explains you can import it manually. This is because the logic with the switch is not written yet.
Related commit: https://github.com/datapress-oss/dp-web/commit/cb073fe04965b9b7f623275f6d3d4cba84d45f1b

**Comment by anymus0** [comment]
@hulitzacsaba 

- set ```<section>``` and ```<div class="card card-body">``` fonts to white that are on a dark background so they'll be visible
- the dark colors should be the following values in hex: 
  * Primary: ```#212121```
  * Secondary: ```#333333```

You can test how colors and fonts look with each other [with this color picker tool](https://www.w3schools.com/colors/colors_picker.asp).
